// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Assignment is the predicate function for assignment builders.
type Assignment func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Statement is the predicate function for statement builders.
type Statement func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
